image:
  name: "ubuntu:latest"

run-test:
  script:
    - apt-get update -y && apt-get install openssh-client git python3 python3-pip python3-venv -y
    - export LANG=C.UTF-8
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GIT_SSH_PRIV_KEY")
    - mkdir -p ~/.ssh
    - ssh-keyscan -p 6022 5.189.144.52 >> ~/.ssh/known_hosts
    - export MW_BUILD_DIR=$PWD
    - cd ..
    - rm -rf lib
    - mkdir -p lib
    - cd lib
    - git clone ssh://git@5.189.144.52:6022/iot1/iotcommons
    - git clone ssh://git@5.189.144.52:6022/iot1/mqtt
    - cd $MW_BUILD_DIR
    - python3 -m venv venv
    - source venv/bin/activate
    - rm -rf .pio
    - pip install --upgrade pip setuptools wheel
    - pip install platformio
    - cp "$RP_ENV" .env
    - source .env
    - pio init --board nodemcuv2
    - pio run
